#!/usr/bin/python
from importlib import import_module
import logging
import re
import sys
import os

sys.path.insert(0, os.path.abspath(__file__).rsplit('/', 1)[0])

import settings


def get_checkers():
    for checker in settings.PRE_CHECKERS:
        cls = checker.rsplit('.', 1)[-1]
        m = checker[:-len(cls)].rsplit('.', 1)[0]
        if m:
            yield getattr(import_module(m), cls)


def check():
    for line in sys.stdin.xreadlines():
        old, new, ref = line.strip().split(' ')

        for regex in settings.SKIPPED_BRANCHES_RE:
            if re.findall(regex, ref):
                logging.info('Skipped: ref "%s" matches "%s".' % (ref, regex))
                continue

        for checker in get_checkers():
            if not checker(old, new, ref).check():
                sys.exit(1)


if __name__ == '__main__':
    check()
    sys.stdout.flush()
