#!/usr/bin/python
import sys
from importlib import import_module

import settings


if __name__ == '__main__':
    checkers = []
    for checker in settings.PRE_CHECKERS:
        cls = checker.rsplit('.', 1)[-1]
        m = checker[:-len(cls)].rsplit('.', 1)[0]
        if m:
            checkers.append(getattr(import_module(m), cls))

    for line in sys.stdin.xreadlines():
        old, new, ref = line.strip().split(' ')

        for checker in checkers:
            if not checker(old, new, ref).check():
                sys.exit(1)

    sys.stdout.flush()
